export { default as Home } from './Home'
export { default as About } from './About'
export { default as Works } from './Works'
export { default as TotalWorks } from './TotalWorks'
export { default as Contact } from './Contact'
